name: fakej
version: '0.1.0.0'
category: Development
author: Brady Ouren
maintainer: brady.ouren@gmail.com
copyright: 2017 Brady Ouren
license: BSD3
github: tippenein/fakej
extra-source-files:
- README.md
default-extensions:
- OverloadedStrings
- NoImplicitPrelude
dependencies:
- protolude >=0.1.6 && <0.2
library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
  - Lib
  dependencies:
  - base >= 4.9
  - megaparsec
executables:
  fakej-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - fakej
tests:
  fakej-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - fakej
    - tasty
    - tasty-hunit
    - tasty-smallcheck
